### ISSUE TITLE
where rainbow visualizer

### ISSUE THREAD

**Issue by home-gihub** [sceleri/amogus#2]
in the readme it has rainbow colours how do you get that

**Comment by reisir** [comment]
If I ever update amogus I'll add it to the main settings but if you want this you can manually go and edit the files. Here's the changes you need to make:

In `@Resources\settings.inc`
```ini
; ; InlineSettings
InlineSetting=#Gradient#
InlinePattern=.*

; ; Peak InlineSettings
PeakInlineSetting=#PeakGradient#
PeakInlinePattern=#InlinePattern#
```

In amogus.ini
```
[grid2]
InlineSetting=#PeakGradient#
InlinePattern=#InlinePattern#

[grid]
InlineSetting=#InlineSetting#
InlinePattern=#InlinePattern#
```

All of these are in the code already, just remove the `;` from the lines to activate them. Save the files and right click amogus > rainmeter > refresh skin
